### ISSUE TITLE
Implement deletion concept

### ISSUE THREAD

**Issue by BlueWaves2** [IT-REX-Platform/course_service#29]
Split this issue and reestimate

## Description
The deletion of courses/chapters/content should be implemented according to the deletion concept https://gits-enpro.readthedocs.io/en/latest/dev-manuals/architecture/deletion_concept.html

Requires dapr pub sub to work.

## Acceptance Criteria

- [ ] if a course is deleted, all its content is deleted ( #30 )
- [ ] if a chapter is deleted, all its content is deleted ( #30  )
- [ ] if a piece of content is deleted, all linked resources are notified and remove the content ( https://github.com/IT-REX-Platform/content_service/issues/26 )
- [ ] update in content service ( https://github.com/IT-REX-Platform/content_service/issues/26 )
- [x] update wiki ( https://github.com/IT-REX-Platform/wiki/issues/58 )
